blastdamage
thegrb93/StarfallEx pull request #1078
Opened 2021-02-06 16:34 UTC by LightRobin

adds blastDamage() function, attacker is automatically set to instance.player so that the player calling the function always shows as the killer, (easy to track down abuse)

2021-02-06 16:41 UTC, adamnejm commented
I feel like this needs permission check, maybe even a delay convar.
Also wouldn't it be possible to trick the kill feed by letting user specify the `inflictor`, or does that rely solely on the `attacker`?

2021-02-06 17:01 UTC, LightRobin commented
i believe it is solely based on the attacker, i cooldown might be good but the reason i though of adding this was to make prop engines that use the blast as propulsion for the pistons, adding a delay would break that possibility

2021-02-06 17:07 UTC, LightRobin commented
what would the permission check check for?, you cant specify which entities the blast will affect

2021-02-06 17:10 UTC, adamnejm commented
> what would the permission check check for?

For server owners to enable / disable / limit this feature.

2021-02-06 22:50 UTC, thegrb93 requested changes

2021-02-06 22:50 UTC, thegrb93 commented on lua/starfall/libs_sh/builtins.lua
> +		checkluatype(damageOrigin, TYPE_VECTOR)
The checkluatype isn't needed since unwrap will do that for you. Use eunwrap instead of ounwrap though.

2021-02-06 23:33 UTC, thegrb93 commented
The last thing I'm worried about is abuse and many servers have wire explosives turned off specifically due to players teleporting explosives around (dumb I know).

2021-02-06 23:55 UTC, LightRobin commented
ye, i think it needs a permission that the owner can set (everyone, admin only, noone) i tried adding it earlier but simply ended up with lua errors, heres the code i used 
`registerPrivilege("blast.create", "Blast damage", "Allows the user to create explosions", { server = { default = 1 } })`
`(in the function) checkpermission(instance, nil, "blast.create")`

was getting this error :
`addons/starfall/lua/starfall/permissions/core.lua:69: attempt to call a nil value`
`stack traceback:`
`    addons/starfall/lua/starfall/permissions/core.lua:69: in function 'checkpermission'`

2021-02-07 00:49 UTC, Vurv78 commented
You weren't trying to create the permission inside the instance, were you?

2021-02-07 03:08 UTC, thegrb93 commented
> 
> 
> ye, i think it needs a permission that the owner can set (everyone, admin only, noone) i tried adding it earlier but simply ended up with lua errors, heres the code i used
> `registerPrivilege("blast.create", "Blast damage", "Allows the user to create explosions", { server = { default = 1 } })`
> `(in the function) checkpermission(instance, nil, "blast.create")`
> 
> was getting this error :
> `addons/starfall/lua/starfall/permissions/core.lua:69: attempt to call a nil value`
> `stack traceback:`
> ` addons/starfall/lua/starfall/permissions/core.lua:69: in function 'checkpermission'`

usergroups = { default = 1 }

2021-02-07 10:17 UTC, LightRobin commented
> You weren't trying to create the permission inside the instance, were you?

Nope, just under the other permissions

2021-02-07 10:47 UTC, LightRobin commented
> usergroups = { default = 1 }
still getting the same error

2021-02-08 04:31 UTC, thegrb93 commented
> 
> 
> > usergroups = { default = 1 }
> > still getting the same error

Looks like the problem is you just need to reload the map since its a new permission and hasn't been set up.

2021-02-08 04:35 UTC, thegrb93 commented
Moved to game lib and rebased to resolve conflicts. Let me know if changes look fine.

2021-02-08 13:34 UTC, LightRobin commented
looks good to me

2021-02-08 15:39 UTC, merged