Call mousewheeled on WorldPanel OnMouseWheeled
thegrb93/StarfallEx pull request #1449
Opened 2023-03-08 10:07 UTC by FancyApricot

Calls mousewheeled after input.enableCursor(true) makes StartCommand's CUserCmd return incorrect values https://wiki.facepunch.com/gmod/gui.EnableScreenClicker

2023-03-09 03:32 UTC, FancyApricot commented
Now I look at this the I dont think the SF.cursorEnabled is needed, I also dont unset it when the hud is disconnected or chip is removed. 
But I dont understand why each instance has a cursorEnabled var, shouldnt it be a global thing?
Like if you spawned 2 chips that both call input.enableCursor(true) and delete 1 of them, then you lose cursor but the remaining instance still has data.cursorEnabled set to true.

2023-03-09 17:51 UTC, thegrb93 commented
It is possible to desync the cursor state from what starfall perceives. I think its up to the user to prevent that. Even with that being a global, a user could desync the state via another addon. A cursor state for each chip is simply the safest and easiest implementation.

2023-03-09 17:53 UTC, thegrb93 commented
I need to investigate if there's a better way to get mouse inputs from the world vgui than detouring its hooks. Could easily conflict with other addons.

2023-03-21 07:15 UTC, thegrb93 commented
https://github.com/Facepunch/garrysmod-issues/issues/5429

2023-03-21 07:20 UTC, thegrb93 requested changes

2023-03-21 07:20 UTC, thegrb93 commented on lua/starfall/libs_sh/input.lua
> +local wpanel = vgui.GetWorldPanel()
Could you change to
```lua
local wpanel = vgui.GetWorldPanel()
local oldOnMouseWheeled = wpanel.OnMouseWheeled or function() end
function wpanel:OnMouseWheeled(delta)
	oldOnMouseWheeled(self, delta)
	for inst, _ in pairs(SF.allInstances) do
		if inst.data.cursorEnabled and haspermission(inst, nil, "input") then
			inst:runScriptHook("mousewheeled", delta)
		end
	end
end
```
and remove the `SF.cursorEnabled = enabled`

2023-03-21 07:21 UTC, thegrb93 commented
Sorry for the long wait. Really didn't feel like gmod for the past few weeks.

2023-03-26 21:12 UTC, merged