Language from default language library from gmod
thegrb93/StarfallEx pull request #1459
Opened 2023-04-17 13:24 UTC by NekerSqu4w

# Before creating pull request
- Move all changes to **separate** branch (Don't use master of your fork).
- **Don't** reuse branches.
- **Don't** sync that branch after creating pull request unless it's really needed. (IE. upstream changed code structure).
- Test it and try fixing bugs ahead.
- If you know about any bugs, make sure to list them in PR message.
- Make sure pull request message informs about **ALL** the changes.
- Your pull request can be work-in-progress if you want others to help you with coding or give you  opinions, just make sure to state it's not ready.
- Try to avoid messing with whitespaces. (Setup your editor properly to follow our style).
- If you find whitespaces that don't follow our style you can fix them in separate commit.
- Read about [github flow](https://guides.github.com/introduction/flow/)
​

# Thank you

Thank you for contributing and helping StarfallEx community!

2023-04-17 14:22 UTC, ANormalTwig commented
Your indentation seems off at your return statements, make sure to use tabs instead of spaces.

2023-04-17 14:23 UTC, NekerSqu4w commented
That what i do, but idk why it's added space like that

2023-04-17 16:51 UTC, UnrealEugene commented
Is it possible to replace existing language phrases? Or to undo these changes?

2023-04-17 17:12 UTC, NekerSqu4w commented
Hmmm, with default language function no, you can only add more query word but you can't modify it,
Or maybe if i do a custom language system maybe

2023-04-17 17:21 UTC, ANormalTwig commented
If you can't undo it modify them then the permission should be defaulted to owner only.

2023-04-17 18:03 UTC, NekerSqu4w commented
.. what the id for owner only ?

2023-04-17 21:11 UTC, thegrb93 commented
I have a feeling adding too much will crash the game. Will need to limit it. Not sure what purpose this is for anyway.

2023-04-20 14:43 UTC, thegrb93 requested changes

2023-04-20 14:43 UTC, thegrb93 commented on lua/starfall/libs_cl/language.lua
> +	language.Add(placeholder,fulltext)
placeholder and fulltext length needs to be limited

2023-08-11 20:04 UTC, thegrb93 commented
Will close this stale PR if no work is done on it.

2023-08-16 03:37 UTC, Vurv78 commented
If we just want a localization library, could be done much better. This is by the same guy that made middleclass, too https://github.com/kikito/i18n.lua

2023-08-16 21:31 UTC, thegrb93 commented
I think they more wanted it in order to manipulate engine strings, but closing due to inactivity.

2023-08-16 21:31 UTC, closed without merging