Cache "nil" permission requests per instance
thegrb93/StarfallEx pull request #1547
Opened 2023-10-31 14:39 UTC by wrefgtzweve

After testing around and seeing if i could improve performance on trace.line i saw that permission requests take up a significant amount of time. After further inspection i noticed that some checks like the trace permission check run each time while there's no need for it.
So i decided to use a cache to improve the speed of perm checks.

Testing using this code:
![image](https://github.com/thegrb93/StarfallEx/assets/69946827/3751266e-d2b9-48ca-a75f-1ab36e8af427)

Before:
![image](https://github.com/thegrb93/StarfallEx/assets/69946827/9cc027f6-bbc5-4861-84c0-5686b25edc9c)

After:
![image](https://github.com/thegrb93/StarfallEx/assets/69946827/4eb63414-abbe-4a14-a446-d730f1227027)

As can be seen, proportionally it takes up significantly less time with the cache in place

2023-10-31 15:16 UTC, wrefgtzweve commented
As a sidenote, im not sure if this will work nicely with permission requests as i wasn't able to find a good spot where i would clear the cache so help might be needed there

2023-10-31 21:18 UTC, thegrb93 commented
Most 'nil' permissions are already cached via https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/permissions/core.lua#L39-L45

This won't work with client permissions because they are 'nil' permissions, but they return different results depending on the owner of the chip.
https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/permissions/providers_cl/client.lua#L16

2023-10-31 21:20 UTC, thegrb93 commented
Actually I guess since the cache is per instance, it would work with client permissions.

2023-10-31 21:21 UTC, thegrb93 commented
If you can reset the cache entry for a permission in all instances in the function, then I think it would work https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/permissions/core.lua#L68

2023-10-31 21:32 UTC, thegrb93 commented
Something like this might be better.

```lua
local cached = instance.permissionCache[key]
if cached~=nil then return cached end

local privilege = P.privileges[key]
if privilege.cacheable then
	local ok, reason = privilege.check(instance, target)
	instance.permissionCache[key] = ok
	if not ok then SF.Throw("Permission " .. key .. ": " .. reason, 3) end
else
	local ok, reason = privilege.check(instance, target)
	if not ok then SF.Throw("Permission " .. key .. ": " .. reason, 3) end
end
```

privilege.cacheable can be set to true in https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/permissions/core.lua#L95 if all of its providers are cacheable. That way we aren't relying on the target var for this logic.

2023-10-31 21:36 UTC, thegrb93 requested changes

2023-10-31 21:36 UTC, thegrb93 commented on lua/starfall/permissions/core.lua
> +		instance.permissionCache = {}
Move `instance.permissionCache = {}` to the instance initialization function.

2023-11-05 23:33 UTC, wrefgtzweve commented
Closing this for now as i cannot replicate the performance gains 💀

2023-11-05 23:33 UTC, closed without merging