Added Entity:getTable() and Entity:getVar()
thegrb93/StarfallEx pull request #1719
Opened 2024-04-20 00:08 UTC by Some1Lambda

- Added Entity:getTable()
- Added Entity:getVar()
- Added the entities.getTable permission required by both getTable and getVar functions, default is Can Tool

2024-04-20 20:24 UTC, thegrb93 commented
this could be way too intrusive. e.g. grabbing the password of a wire keypads, grabbing code from starfall/e2 chips. The permission helps but still needs to be carefully considered

2024-04-20 22:46 UTC, Some1Lambda commented
Maybe we could make it admin only by default, or instead just screw the permission and only allow it on the player's own entities?

2024-04-25 06:44 UTC, thegrb93 approved these changes
I gotta test these

2024-05-06 08:26 UTC, thegrb93 commented
I think this one will need to be admin/superuser only.

2024-05-28 18:20 UTC, thegrb93 requested changes

2024-05-28 18:20 UTC, thegrb93 commented on lua/starfall/libs_sv/entities.lua
> +--- Returns entity's table.
```suggestion
--- Returns entity's glua table containing internal glua variables about the entity
```

2024-05-28 18:20 UTC, thegrb93 commented on lua/starfall/libs_sv/entities.lua
> +--- Returns a variable from the entity's table.
```suggestion
--- Returns a variable from the entity's internal glua table.
```

2024-05-28 18:39 UTC, thegrb93 commented
I've been procrastinating... will try this asap

2024-05-29 00:40 UTC, thegrb93 commented
My main worry is using it on a starfall entity and cloning its instance might give access to something really bad or cause something really bad. I'm setting it to admin only for now.

2024-05-29 00:42 UTC, thegrb93 approved these changes

2024-05-29 00:42 UTC, merged