Add optional input/output descriptions arguments
thegrb93/StarfallEx pull request #1768
Opened 2024-06-09 00:40 UTC by marchc1

Adds an optional third argument to wire.adjustInputs and wire.adjustOutputs for Wiremod IO descriptions.

![image](https://github.com/thegrb93/StarfallEx/assets/106459595/67695c81-cb48-4eac-8c62-cae9ca29c95a)

2024-06-09 10:18 UTC, thegrb93 requested changes

2024-06-09 10:18 UTC, thegrb93 commented on lua/starfall/libs_sv/wire.lua
> +		checkluatype(descriptions, TYPE_TABLE)
use instance.Unsanitize

2024-06-09 21:22 UTC, TheVayt commented
Adding this functionality to `wire.adjustPorts` in some way would be nice too.
Also make sure that this new parameter is shown as optional in docs

2024-06-14 07:59 UTC, thegrb93 approved these changes

2024-06-14 07:59 UTC, merged