fix holograms not fixing renderbounds after fullupdate
thegrb93/StarfallEx pull request #1877
Opened 2024-10-20 00:28 UTC by yingKatsu

#1876 

i notice before that the existing code for setting render bounds didnt check for if the networkentitycreated ent was a hologram? is this hook in hologram cl_init also for custom props too?

# Before creating pull request
- Move all changes to **separate** branch (Don't use master of your fork).
- **Don't** reuse branches.
- **Don't** sync that branch after creating pull request unless it's really needed. (IE. upstream changed code structure).
- Test it and try fixing bugs ahead.
- If you know about any bugs, make sure to list them in PR message.
- Make sure pull request message informs about **ALL** the changes.
- Your pull request can be work-in-progress if you want others to help you with coding or give you  opinions, just make sure to state it's not ready.
- Try to avoid messing with whitespaces. (Setup your editor properly to follow our style).
- If you find whitespaces that don't follow our style you can fix them in separate commit.
- Read about [github flow](https://guides.github.com/introduction/flow/)
​

# Thank you

Thank you for contributing and helping StarfallEx community!

2024-10-20 11:23 UTC, thegrb93 requested changes

2024-10-20 11:23 UTC, thegrb93 commented on lua/entities/starfall_hologram/cl_init.lua
> +	if holo.IsSFHologram then
sf_userrenderbounds should work for all entities, not just holograms

2024-10-20 11:23 UTC, thegrb93 commented on lua/entities/starfall_hologram/cl_init.lua
> +			holo:OnScaleChanged(nil, nil, holo:GetScale())
This OnScaleChanged call isn't doing anything more that isn't already being done here. What's the point of adding it?

2024-10-20 12:58 UTC, yingKatsu commented
OnScaleChanged contains 
```
		local mins, maxs = self:GetModelBounds()
		if mins then
			self:SetRenderBounds(mins * scale, maxs * scale)
		end
```
which is core to fixing #1876. I just took it from the ENT:Initialize function because it wasnt being called when holograms are destroyed and remade clientside due to fullupdates. I ran this current code live and it fixed the problem displayed in the video in the issue.

However, upon reading through OnScaleChanged, it does contain overlap with code already running in this hook. I will just call this specific excerpt then instead of the whole function.

2024-10-20 13:25 UTC, yingKatsu commented
video showcasing live vs my patch:
https://cdn.discordapp.com/attachments/934077057707704372/1297551015087702116/2024-10-20_08-22-56.mp4?ex=6716560d&is=6715048d&hm=ebed8b78bb28c2dcd4cc7312d8874bb947114f90358feb5901f84a508f94d4a5&

2024-10-20 13:33 UTC, yingKatsu commented
video showcasing live vs my patch:
https://cdn.discordapp.com/attachments/934077057707704372/1297553036918521926/2024-10-20_08-31-26.mp4?ex=671657ef&is=6715066f&hm=ff7fc0547213a20825cdab7e85520e3b13a5bfe3c58e423364aa8dd8143d4389&

2024-10-21 01:09 UTC, thegrb93 approved these changes

2024-10-21 01:10 UTC, merged